from two_way import TwoWay

t = TwoWay(13)
t.put(25, 'grape')
t.put(37, 'apple')
t.put(18, 'banana')
t.put(55, 'cherry')
t.put(22, 'mango')
t.put(35, 'lime')
t.put(50, 'orange')
t.put(63, 'watermelon')
t.put(16, 'berry')
t.put(48, 'honey dew')
t.put(10, 'kiwi')
t.put(96, 'lemon')
t.put(53, 'strawberry')
t.put(65, 'pineapple')
t.put(81, 'avocado')

print('해시 테이블 : ')
t.print_table()
t.put(25, 'apricot')
t.put(35, 'pear')
print('탐색 결과: ')
print('50의 data = ', t.get(50))
print('63의 data = ', t.get(63))
print('해시 테이블 : ')
t.print_table()
